config/routes.rb
Rails.application.routes.draw do
  resources :survey_data
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'survey_data#index'

  namespace :api , defaults: {format: 'json'} do
    get 'v1/get_mobile_list'
  end

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/survey_datum.rb
class SurveyDatum < ApplicationRecord
	validates :phone_no,:presence => true,
                 :numericality => true,
                 :length => { :minimum => 10, :maximum => 15 }
    validates_format_of :email_id, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i    
    validates_format_of :name, :with => /\w+/, :message => "can only contain characters"  
end

app/controllers/api/v1_controller.rb
class Api::V1Controller < ApplicationController
	skip_before_filter :verify_authenticity_token, :only => [:is_login,:add_material]
	
	def get_mobile_list
		mobile_list = SurveyDatum.where(age: params[:age],family_montly_income: params[:family_montly_income]).collect(&:mobile_phone)
		render json: {code: "200", status: true, message: "success" , mobile_list: mobile_list}
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/survey_data_controller.rb
class SurveyDataController < ApplicationController
  before_action :set_survey_datum, only: [:show, :edit, :update, :destroy]

  # GET /survey_data
  # GET /survey_data.json
  def index
    @survey_data = SurveyDatum.all
  end

  # GET /survey_data/1
  # GET /survey_data/1.json
  def show
  end

  # GET /survey_data/new
  def new
    @survey_datum = SurveyDatum.new
  end

  # GET /survey_data/1/edit
  def edit
  end

  # POST /survey_data
  # POST /survey_data.json
  def create
    @survey_datum = SurveyDatum.new(survey_datum_params)

    respond_to do |format|
      if @survey_datum.save
        format.html { redirect_to @survey_datum, notice: 'Survey datum was successfully created.' }
        format.json { render :show, status: :created, location: @survey_datum }
      else
        format.html { render :new }
        format.json { render json: @survey_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /survey_data/1
  # PATCH/PUT /survey_data/1.json
  def update
    respond_to do |format|
      if @survey_datum.update(survey_datum_params)
        format.html { redirect_to @survey_datum, notice: 'Survey datum was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey_datum }
      else
        format.html { render :edit }
        format.json { render json: @survey_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survey_data/1
  # DELETE /survey_data/1.json
  def destroy
    @survey_datum.destroy
    respond_to do |format|
      format.html { redirect_to survey_data_url, notice: 'Survey datum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey_datum
      @survey_datum = SurveyDatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_datum_params
      params.require(:survey_datum).permit(:state, :city, :geography, :name, :phone_no, :address, :number_of_family_member, :gender, :age, :caste, :family_montly_income, :occupation, :monthly_recharge_spend, :internet_usage, :hospital, :school, :vehicle, :computer_usage, :whatsup_usage, :email_id, :mobile_phone, :facebook_account)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/survey_data_helper.rb
module SurveyDataHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Survey</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/survey_data/_form.html.erb
<%= form_for(survey_datum) do |f| %>
  <% if survey_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survey_datum.errors.count, "error") %> prohibited this survey_datum from being saved:</h2>

      <ul>
      <% survey_datum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
    <div class= "form-group">
      <h3> About Yourself </h3>
    </div>    
    
       <p>
          <b>1.</b>  <%= f.label :state, "State" %>
          <%= f.text_field :state , :class=>"form-contro", :placeholder=>"state"%>       
          <b>2.</b>  <%= f.label :city, "Vidhan sabha/City" %>
          <%= f.text_field :city %>
          <b>3.</b>  <%= f.label :geography, "Geography" %>

              <% ['Urban', 'Rural'].each do |geography| %>
                  <%= f.radio_button :geography, geography%>
                  <%= geography%>
              <% end %>
        </p>     
                                  
       <p>
          <b>4.</b>  <%= f.label :name, "Name" %>
          <%= f.text_field :name %>
          <b>5.</b>  <%= f.label :phone_no, "Phone No" %>
          <%= f.text_field :phone_no %>
       </p>
       <p>
          <b>6.</b>  <%= f.label :address, "Address" %>
          <%= f.text_area :address %>

          <b>7.</b>  <%= f.label :number_of_family_member, "Number of Family Member" %>
          <%= f.text_field :number_of_family_member %>
          
          <b>8.</b>  <%= f.label :gender, "Gender" %>

                <%= f.radio_button :gender, 'male' %>&nbsp;Male

                <%= f.radio_button :gender, 'female' %>&nbsp;Female
       </p>
       <p>
          <b>9.</b> <%= f.label :age, "Age" %>
               <% [ '12-17', '18-25', '26-35', '36-50', '50-60','60 & above' ].each do |age| %>
                 <%= f.radio_button 'age',  age %>
                     <%= age%>
                <% end %>
       </p>
       <p>
          <b>10.</b>  <%= f.label :caste, "Caste" %>
               <% [ 'ST', 'SC', 'Muslim', 'OBC', 'Vaish','Shatriya' ].each do |caste| %>
                 <%= f.radio_button 'caste', caste %>
                     <%= caste%>
                <% end %>
       </p>
       <p>
          <b>11.</b>  <%= f.label :family_montly_income, "Family Monthly Income" %>
              <% [ 'Below 5,000', '5-10,000', '10-20,000', '20-30,000', '30,000 & above' ].each do |family_montly_income| %>
                 <%= f.radio_button 'family_montly_income', family_montly_income %>
                     <%= family_montly_income%>
              <% end %>
       </p>
       <p>
          <b>12.</b>  <%= f.label :occupation, "Occupation" %>
               <% ['unemployed','housewife','student','worker','farmer','buisness','private service','govt service'].each do |occupation| %>
                 <%= f.radio_button 'occupation',  occupation %>
                     <%= occupation%>
               <% end %>
       </p>
       <p>
          <b>13.</b>  <%= f.label :monthly_recharge_spend, "Monthly Recharge Spend" %>
               <% ['0-100','100-200','200-500','500 & above'].each do |monthly_recharge_spend| %>
                 <%= f.radio_button 'monthly_recharge_spend', monthly_recharge_spend %>
                     <%= monthly_recharge_spend%>
               <% end %>
       </p>
       <p>
          <b>14.</b>  <%= f.label :internet_usage, "Internet Usage" %>
               <% ['home','office','panchyat','cyber_cafe','mobile','do not use'].each do |internet_usage| %>
                 <%= f.radio_button 'internet_usage',  internet_usage %>
                     <%= internet_usage%>
               <% end %>
       </p>
       <p>
          <b>15.</b>  <%= f.label :hospital, "Hospital" %>
               <% ['government','private','self medication','local doctor'].each do |hospital| %>
                 <%= f.radio_button 'hospital', hospital %>
                     <%= hospital%>
               <% end %>
       </p>
       <p>
          <b>16.</b>  <%= f.label :school, "School" %>
               <% ['government','private','tution','not studying'].each do |school| %>
                 <%= f.radio_button 'school',  school %>
                     <%= school%>
               <% end %>
       </p>
       <p>
          <b>17.</b>  <%= f.label :vehicle, "Vehicle" %>
               <% ['cycle','motor','car','public transport'].each do |vehicle| %>
                 <%= f.radio_button 'vehicle', vehicle %>
                     <%= vehicle%>
               <% end %>
       </p>
       <p>
          <b>18.</b>  <%= f.label :computer_usage, "Computer Usage" %>
            <%= f.radio_button :computer_usage, 'yes' %> Yes
            <%= f.radio_button :computer_usage, 'no' %> No
           <b>19.</b>  <%= f.label :facebook_account, "Facebook Account" %>
             <%= f.radio_button :facebook_account, 'yes' %> Yes
             <%= f.radio_button :facebook_account, 'no' %> No
          <b>20.</b>  <%= f.label :whatsup_usage, "Whatsup Usage" %>
            <%= f.radio_button :whatsup_usage, 'yes' %> Yes
            <%= f.radio_button :whatsup_usage, 'yes' %> No
       </p>
       <p>
          <b>21.</b>  <%= f.label :email_id, "Email Id" %>
          <%= f.email_field :email_id %>
       </p>

      <h2>Which are your choice of 'incredible brand'</h2>
       <p>
          <b>22.</b>  <%= f.label :mobile_phone, "Mobile Phone" %>
               <% ['samsung','lava','micromax','nokia'].each do |mobile_phone| %>
                 <%= f.radio_button 'mobile_phone', mobile_phone %>
                     <%= mobile_phone%>
               <% end %>
       </p>              
 <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<!-- <script type="text/javascript">
  
$('#new_survey_datum').submit(function(e) {
            e.preventDefault();
            if(!$('#survey_datum_phone_no').val().match('[0-9]{10}'))  {
                alert("Please put 10 digit mobile number");
                return;
            }  

        });
</script> -->

app/views/survey_data/edit.html.erb
<h1>Editing Survey Datum</h1>

<%= render 'form', survey_datum: @survey_datum %>

<%= link_to 'Show', @survey_datum %> |
<%= link_to 'Back', survey_data_path %>

app/views/survey_data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Survey Data</h1>

<table class="table table-hover table table-bordered table table-condensed table-responsive">
  <thead>
    <tr>
      <th>State</th>
      <th>City</th>
      <th>Geography</th>
      <th>Name</th>
      <th>Phone no</th>
      <th>Address</th>
      <th>Number of family member</th>
      <th>Gender</th>
      <th>Age</th>
      <th>Caste</th>
      <th>Family montly income</th>
      <th>Occupation</th>
      <th>Monthly recharge spend</th>
      <th>Internet usage</th>
      <th>Hospital</th>
      <th>School</th>
      <th>Vehicle</th>
      <th>Computer usage</th>
      <th>Whatsup usage</th>
      <th>Email</th>
      <th>Mobile phone</th>
      <th>Facebook account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @survey_data.each do |survey_datum| %>
      <tr>
        <td><%= survey_datum.state %></td>
        <td><%= survey_datum.city %></td>
        <td><%= survey_datum.geography %></td>
        <td><%= survey_datum.name %></td>
        <td><%= survey_datum.phone_no %></td>
        <td><%= survey_datum.address %></td>
        <td><%= survey_datum.number_of_family_member %></td>
        <td><%= survey_datum.gender %></td>
        <td><%= survey_datum.age %></td>
        <td><%= survey_datum.caste %></td>
        <td><%= survey_datum.family_montly_income %></td>
        <td><%= survey_datum.occupation %></td>
        <td><%= survey_datum.monthly_recharge_spend %></td>
        <td><%= survey_datum.internet_usage %></td>
        <td><%= survey_datum.hospital %></td>
        <td><%= survey_datum.school %></td>
        <td><%= survey_datum.vehicle %></td>
        <td><%= survey_datum.computer_usage %></td>
        <td><%= survey_datum.whatsup_usage %></td>
        <td><%= survey_datum.email_id %></td>
        <td><%= survey_datum.mobile_phone %></td>
        <td><%= survey_datum.facebook_account %></td>
        <td><%= link_to 'Show', survey_datum %></td>
        <td><%= link_to 'Edit', edit_survey_datum_path(survey_datum) %></td>
        <td><%= link_to 'Destroy', survey_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey Datum', new_survey_datum_path %>

app/views/survey_data/new.html.erb
<h3>New Survey Datum</h3>

<%= render 'form', survey_datum: @survey_datum %>

<%= link_to 'Back', survey_data_path %>

app/views/survey_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State:</strong>
  <%= @survey_datum.state %>
</p>

<p>
  <strong>City:</strong>
  <%= @survey_datum.city %>
</p>

<p>
  <strong>Geography:</strong>
  <%= @survey_datum.geography %>
</p>

<p>
  <strong>Name:</strong>
  <%= @survey_datum.name %>
</p>

<p>
  <strong>Phone no:</strong>
  <%= @survey_datum.phone_no %>
</p>

<p>
  <strong>Address:</strong>
  <%= @survey_datum.address %>
</p>

<p>
  <strong>Number of family member:</strong>
  <%= @survey_datum.number_of_family_member %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @survey_datum.gender %>
</p>

<p>
  <strong>Age:</strong>
  <%= @survey_datum.age %>
</p>

<p>
  <strong>Caste:</strong>
  <%= @survey_datum.caste %>
</p>

<p>
  <strong>Family montly income:</strong>
  <%= @survey_datum.family_montly_income %>
</p>

<p>
  <strong>Occupation:</strong>
  <%= @survey_datum.occupation %>
</p>

<p>
  <strong>Monthly recharge spend:</strong>
  <%= @survey_datum.monthly_recharge_spend %>
</p>

<p>
  <strong>Internet usage:</strong>
  <%= @survey_datum.internet_usage %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @survey_datum.hospital %>
</p>

<p>
  <strong>School:</strong>
  <%= @survey_datum.school %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @survey_datum.vehicle %>
</p>

<p>
  <strong>Computer usage:</strong>
  <%= @survey_datum.computer_usage %>
</p>

<p>
  <strong>Whatsup usage:</strong>
  <%= @survey_datum.whatsup_usage %>
</p>

<p>
  <strong>Email:</strong>
  <%= @survey_datum.email_id %>
</p>

<p>
  <strong>Mobile phone:</strong>
  <%= @survey_datum.mobile_phone %>
</p>

<p>
  <strong>Facebook account:</strong>
  <%= @survey_datum.facebook_account %>
</p>

<%= link_to 'Edit', edit_survey_datum_path(@survey_datum) %> |
<%= link_to 'Back', survey_data_path %>